config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  resources :breeds
  
  root 'dogs#index'
  

end

app/models/breed.rb
class Breed < ActiveRecord::Base
    has_many :dog
end

app/models/dog.rb
class Dog < ActiveRecord::Base
    belongs_to :breed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: [:show, :edit, :update, :destroy]

  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1
  # PATCH/PUT /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed.destroy
    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breed_params
      params.require(:breed).permit(:name, :porte, :peso, :caracteristicas)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:nome, :idade, :peso)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/breeds/_form.html.erb
<%= form_for(@breed) do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :porte %><br>
    <%= f.text_field :porte %>
  </div>
  <div class="field">
    <%= f.label :peso %><br>
    <%= f.number_field :peso %>
  </div>
  <div class="field">
    <%= f.label :caracteristicas %><br>
    <%= f.text_area :caracteristicas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing Breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Porte</th>
      <th>Peso</th>
      <th>Caracteristicas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeds.each do |breed| %>
      <tr>
        <td><%= breed.name %></td>
        <td><%= breed.porte %></td>
        <td><%= breed.peso %></td>
        <td><%= breed.caracteristicas %></td>
        <td><%= link_to 'Show', breed %></td>
        <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
        <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breed', new_breed_path %>

app/views/breeds/new.html.erb
<h1>New Breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breed.name %>
</p>

<p>
  <strong>Porte:</strong>
  <%= @breed.porte %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @breed.peso %>
</p>

<p>
  <strong>Caracteristicas:</strong>
  <%= @breed.caracteristicas %>
</p>

<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :peso %><br>
    <%= f.number_field :peso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Peso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.nome %></td>
        <td><%= dog.idade %></td>
        <td><%= dog.peso %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @dog.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @dog.idade %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @dog.peso %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>